provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure:
    BINSTAR_TOKEN: oE15EAmA0S8idq8/WmFhoBqRxbwN+PD+UsYzxuVCBIUKdYfjOPb8YuyR0GW+vifsfJZFIThFyffzmMl3JWkrkaIPlo7zJOXe+nbukAqoICXoi+20ly3/rosiCktM6A+E7EmjAB/KL/7/Pj2UM4yfiKwOK2w+o6RDbdr47LiAYPZQ+a5jQDUBzaViXNCH17zWVDaMCFuNQIpNRBFaalZMpskywMG28WpMDAMt2oFjDxvjHH4Ws/qrvlCoDDcPjA6OseO/D0FevCxzFeuZb3QxRfJNyzzKxbX8L+CEtytShhcfmaD9k1PbHuCT6hE0dfoc+VMpzBCHrhkSXCWBqtT+shWPWSZtOobzEC6k+xmJ+TSb1y+UBWLOe6xGMXm8TMzLo4qghIliz0b1nqdBLTt+gQsQpXrH+P3zBrNLPRRDa/0M34ruouB+/a51d0RGEFNqv0YStSqamA/11rsiiPf7ymTSggpj/UGqliqDxZzLciuFVrm50sSOB8hf+Uj2ewOT3ONthv4HkhUqvEJesPCPQjINBHGDe3G47/p7IIklmW1WPP/zoix2fM/gOClRJ5KGy93jGZWfzFmPF1Fn4Ldx8JDoNTwNKov4qb+0mcbCMBsEyjHREflk0td4+Zbrenbkz13NH2tLZeS1xaht2Q6qHF4hEb9pOWIbBOxX4aCAHK8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
